[package]
name = "piccy-picky"
version = "0.1.0"
edition = "2024"

[dependencies]
objc = "0.2"
objc-sys = "0.3"
objc-foundation = "0.1"
objc_id = "0.1"
image = "0.24"
iterm2img = "0.1"
rand = "0.8"
libc = "0.2"
base64 = "0.21"
